version: '3'
services:
  my-nodejs-app:
    build: .
    image: my-nodejs-app:latest
    ports:
      - "3000:3251"
    env_file: .env  # 使用 .env 檔案中的環境變數
    networks:
      - mynetwork
    depends_on:
      - sql1

  sql1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"  # 設定 SQL Server 的 sa 用戶密碼
    ports:
      - "1433:1433"
    hostname: sql1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
